SCALING = {
    4: 200,
    6: 135,
    8: 100, 
    16: 50
}

WALL_T = 3
WALL_COLOR = (30, 30, 30)
FREE_COLOR = (220, 220, 220)
ROBOT_COLOR = (200, 30, 30)

MAZES = {
    4:     ["TFFT|TFFF|TTTF|TTFT",
            "FTFT|FFFT|TTFF|FTFT",
            "FTFT|FFTT|FTTF|FTTT",
            "FFTT|TTTF|TFTT|TTTF"],
            
    6: ['TFTT|TFTF|TFTF|TTFF|TTFT|TTTT',
         'TFTT|TFFF|TFFF|FTTF|FFFT|TTTF', 
         'TTTT|FTTT|FFFT|TTFF|FFFT|TTFF', 
         'TFFT|TFTF|FFTF|FTTF|FTFT|FTFT', 
         'FTFT|TTTT|TFTT|TTTF|FTFT|FTTT', 
         'FFTT|TTTF|TTTT|TTTT|FTTT|TTTT'],
    8: ['TTTT|TFTT|TTFF|TTTT|TTFT|TTTT|TFFT|TTFF', 'TTFT|TFFT|FTFF|TFTT|FTTF|TTFT|FFTT|FTTF', 'FFFT|FFTF|FFFF|TFTF|TTTF|FTFT|TTTT|TTFT', 'FFTT|TTFF|FTFT|TFFT|TTFF|FFFT|TTTF|FTTT', 'TTTT|FFTT|FTFF|FFFT|FFTF|FFTF|TTTF|TTTT', 'TFTT|TFFF|FTTF|FTFT|TFTT|TTFF|TTTT|TTTT', 'TTTT|FFFT|TTTF|FFFT|TTTF|FTFT|TFFT|TTFF', 'TFTT|FFTF|TFTF|FTTF|TTTT|FTTT|FTTT|FTTT'],
    16: ['TTTT|TFTT|TFTF|TFFF|TFTF|TTTF|TFFT|TFFF|TTFF|TFTT|TFTF|TTTF|TTFT|TTFT|TTFT|TTFT', 'TTTT|TFTT|TFFF|FTTF|TTFT|TFFT|FFFF|FTTF|FFTT|TTTF|TFTT|TFTF|FTFF|FFFT|FTFF|FTTT', 'TFFT|TFTF|FFFF|TFTF|FFTF|FTFF|FFFT|TTTF|TTFT|TTTT|TTFT|TTFT|FFFT|FFFF|FFFF|TTTF', 'FFTT|TTTF|FTFT|TTFT|TTTT|FFTT|FFFF|TFFF|FFTF|TFFF|FFFF|FFTF|FFFF|FTFF|FFFT|TTFF', 'TFTT|TFTF|FTTF|FFFT|TTFF|TFTT|FFTF|FFFF|TFTF|FFTF|FTFF|TFFT|FTFF|FTTT|FFFT|FTFF', 'TFTT|TFTF|TFFF|FFTF|FTTF|TFTT|TFTF|FTTF|TTTT|TTTT|FTFT|FTFT|FTTT|TFTT|FFFF|FTFF', 'TFTT|TTFF|FFFT|TTFF|TTFT|TFFT|TTFF|TTTT|TTTT|TTTT|FTTT|FFTT|TFFF|TTFF|FTFT|FTTT', 'TFTT|FTTF|FFFT|FTFF|FFTT|FFTF|FTFF|TFFT|TTFF|TFTT|TTTF|TTFT|FFTT|FFFF|FFTF|TTTF', 'TTFT|TFFT|FTTF|FFFT|TFTF|TFFF|FTTF|FFFT|FFTF|TFTF|TTFF|FFTT|TFTF|FFFF|TFFF|TTFF', 'FFTT|FTFF|TFTT|FTFF|TTFT|FTTT|TTTT|FFFT|TTFF|TFTT|FTTF|TFTT|TFTF|FFFF|FFTF|FTFF', 'TTTT|FTFT|TTTT|FTFT|FFTT|TFFF|TFTF|FTFF|FTFT|TFTT|TTTF|TTFT|TTFT|FTFT|TFTT|FTTF', 'TTFT|FFTT|TTTF|FFFT|TTTF|FFFT|TFFF|FTFF|FTTT|TTTT|TFFT|FFTF|FFTF|FFFF|TFFF|TTFF', 'FFTT|TFFF|TFFF|FTTF|TFTT|FTFF|FFFT|FFTF|TFTF|TFFF|FTTF|TTFT|TFFT|FTTF|FTTT|FTTT', 'TTTT|FFTT|FFTF|TFFF|TTTF|FFFT|FFFF|TFFF|TFTF|FTFF|TFTT|FTTF|FFFT|TTFF|TTTT|TTFT', 'TTTT|TFFT|TTTF|FFFT|TFTF|FTTF|FTFT|FTFT|TTFT|FFTT|TTTF|TFFT|FFTF|FFTF|TTTF|FTTT', 'TFTT|FFTF|TFTF|FFTF|TFTF|TFTF|FFTF|FTTF|FFTT|TTTF|TFTT|FTTF|TFTT|TTTF|TFTT|TTTF'],
}
