SCALING = {
    4: 200,
    6: 135,
    8: 100, 
    12: 67,
    16: 50
}

WALL_T = 3
WALL_COLOR = (30, 30, 30)
FREE_COLOR = (220, 220, 220)
ROBOT_COLOR = (200, 30, 30)
# Top , Right, Bottom , Left
MAZES = {
    '4-1': ["TFFT|TFFF|TTTF|TTFT",
            "FTFT|FFFT|TTFF|FTFT",
            "FTFT|FFTT|FTTF|FTFT",
            "FFTT|TTTF|TFTT|FTTF"],
    '4-2': [
        "TFFT|TFTF|TFFF|TTTF",
        "FTFT|TFFT|FTFF|TFFT",
        "FTFT|FFTT|FTTF|FTFT",
        "FFTT|TFTF|TFTF|FTTF"
    ],
    '6-1': [
        "TFTT|TFTF|TFFF|TFTF|TFTF|TTFF",
        "TTFF|TFFT|FFFF|TTTF|TTFT|FTFT",
        "FTFT|FTFT|FFFT|TTFF|FFFT|FTFF",
        "FFFT|FTFF|FFTT|FTTF|FTFT|FTFT",
        "FTFT|FFTT|TTFF|TFTT|FFFF|FTTF",
        "FFTT|TFTF|FTTF|TFTT|FFTF|TTTF"
    ],
    '6-2': [
        "TFFT|TFTF|TTTF|TFFT|TFTF|TTFF",
        "FTFT|TFFT|TFTF|FFFF|TTTF|FTFT",
        "FTFT|FTFT|TFFT|FTFF|TFTT|FTFF",
        "FFFT|FTFF|FFTT|FTTF|TFFT|FTTF",
        "FTFT|FFTT|TFFF|TFTF|FFTF|TTFF",
        "FFTT|TFTF|FFTF|TFTF|TFTF|FTTF"
    ],
    '8-1': [
        "TTFT|TFFF|TFTF|TFTF|TFTF|TFFF|TTFT|TTFT",
        "TFTF|TFTT|TFTF|TFFF|TFTF|TFTF|TTFF|TFFT",
        "TFTF|TTFF|TFFT|FFFF|TTTF|TTFF|FTFT|TFFT",
        "TTFF|FTFT|FTFT|FFFT|TTFF|FFFT|FTFF|TFFT",
        "TTFF|FFTT|FTFF|FFTT|FTTF|FTFT|FTFT|TFFT",
        "TFFF|TTFT|FFTT|TTFF|TFTT|FFFF|FTTF|TFTF",
        "TTFF|FFTT|TFTF|FTTF|TFTT|FFTF|TTTF|TFTF",
        "FFTT|TFFF|TFTF|TFTT|FFTF|TFTF|TFFF|TTTT"
    ],
    '8-2': [
        "TTTF|TFTF|TFFF|TTFT|TFTF|TTFT|TFTF|TTTF",
        "TTFF|TFFT|TFTF|TTTF|TFFT|TFTF|TTFF|TFFT",
        "TFFF|FTFT|TFFT|TFTF|FFFF|TTTF|FTFT|TFFF",
        "TTFF|FTFT|FTFT|TFFT|FTFF|TFTT|FTFF|TFFT",
        "TTFF|FFFT|FTFF|FFTT|FTTF|TFFT|FTTF|TFFT",
        "TTFF|FTFT|FFTT|TFFF|TFTF|FFTF|TTFF|TFFF",
        "TTFF|FFTT|TFTF|FFTF|TFTF|TFTF|FTTF|TFFF",
        "FFTT|TFTF|FTTF|TFTT|FFTF|TTTF|FTFF|FFTT"
    ],

   '12-1': [
        "TFFF|TTTF|FFFT|TFTF|TFTF|FTTF|TFTT|FTTF|TFTF|TFTF|FTTF|TFFF",
        "FFFF|FTTF|TFTF|TFFF|TFTF|TFFF|FTFF|TFTT|TFTF|FFTF|TFTF|FTTF",
        "TFTF|TFTF|TTFT|TFFF|TFTF|TFTF|TFTF|TFFF|TTFT|TTFT|TFTF|TFTF",
        "TFTF|TFTF|TFTF|TFTT|TFTF|TFFF|TFTF|TFTF|TTFF|TFFT|TFTF|TFTF",
        "TFTF|FFTF|TTFF|TFFT|TFTF|FFFF|TTTF|TTFF|FTFT|TFFT|TFTF|TFTF",
        "FFTF|TTTF|TTFT|FTFT|FTFT|FFFT|TTFF|FFFT|FTFF|TFFT|TFTF|TFTF",
        "TFTF|FTTF|TTFT|FFTT|FTFF|FFTT|FTTF|FTFT|FTFT|TFFT|TFTF|TFTF",
        "FFTF|TTTF|TFFT|TTFT|FFTT|TTFF|TFTT|FFFF|FTTF|TFTF|TFTF|TFTF",
        "TFTF|FTTF|TTFT|FFTT|TFTF|FTTF|TFTT|FFTF|TTTF|TFTF|TFTF|TFTF",
        "FFTF|TTTF|FFTT|TFFF|TFTF|TFTT|FFTF|TFTF|TFFF|TTTT|TFTF|TFTF",
        "FTTF|TTTF|TFTT|TTTF|TFTT|TFTF|TFTF|TFTF|FTTF|TFTF|FTTF|TFTF",
        "TFFF|FTTF|TFTF|TFTF|FTTF|TFTF|FTTF|TFTF|TTTF|FTTT|TFTF|TFFF"
    ],




    # '8-0':     ['TTTT|TFTT|TTFF|TTTT|TTFT|TTTT|TFFT|TTFF',
    #         'TTFT|TFFT|FTFF|TFTT|FTTF|TTFT|FFTT|FTTF',
    #         'FFFT|FFTF|FFFF|TFTF|TTTF|FTFT|TTTT|TTFT',
    #         'FFTT|TTFF|FTFT|TFFT|TTFF|FFFT|TTTF|FTTT', 
    #         'TTTT|FFTT|FTFF|FFFT|FFTF|FFTF|TTTF|TTTT', 
    #         'TFTT|TFFF|FTTF|FTFT|TFTT|TTFF|TTTT|TTTT',
    #         'TTTT|FFFT|TTTF|FFFT|TTTF|FTFT|TFFT|TTFF',
    #         'TFTT|FFTF|TFTF|FTTF|TTTT|FTTT|FTTT|FTTT'],

    # '16-1': ['TTTT|TFTT|TFTF|TFFF|TFTF|TTTF|TFFT|TFFF|TTFF|TFTT|TFTF|TTTF|TTFT|TTFT|TTFT|TTFT',
    #      'TTTT|TFTT|TFFF|FTTF|TTFT|TFFT|FFFF|FTTF|FFTT|TTTF|TFTT|TFTF|FTFF|FFFT|FTFF|FTTT', 
    #      'TFFT|TFTF|FFFF|TFTF|FFTF|FTFF|FFFT|TTTF|TTFT|TTTT|TTFT|TTFT|FFFT|FFFF|FFFF|TTTF', 
    #      'FFTT|TTTF|FTFT|TTFT|TTTT|FFTT|FFFF|TFFF|FFTF|TFFF|FFFF|FFTF|FFFF|FTFF|FFFT|TTFF', 
    #      'TFTT|TFTF|FTTF|FFFT|TTFF|TFTT|FFTF|FFFF|TFTF|FFTF|FTFF|TFFT|FTFF|FTTT|FFFT|FTFF', 
    #      'TFTT|TFTF|TFFF|FFTF|FTTF|TFTT|TFTF|FTTF|TTTT|TTTT|FTFT|FTFT|FTTT|TFTT|FFFF|FTFF', 
    #      'TFTT|TTFF|FFFT|TTFF|TTFT|TFFT|TTFF|TTTT|TTTT|TTTT|FTTT|FFTT|TFFF|TTFF|FTFT|FTTT', 
    #      'TFTT|FTTF|FFFT|FTFF|FFTT|FFTF|FTFF|TFFT|TTFF|TFTT|TTTF|TTFT|FFTT|FFFF|FFTF|TTTF', 
    #      'TTFT|TFFT|FTTF|FFFT|TFTF|TFFF|FTTF|FFFT|FFTF|TFTF|TTFF|FFTT|TFTF|FFFF|TFFF|TTFF', 
    #      'FFTT|FTFF|TFTT|FTFF|TTFT|FTTT|TTTT|FFFT|TTFF|TFTT|FTTF|TFTT|TFTF|FFFF|FFTF|FTFF', 
    #      'TTTT|FTFT|TTTT|FTFT|FFTT|TFFF|TFTF|FTFF|FTFT|TFTT|TTTF|TTFT|TTFT|FTFT|TFTT|FTTF', 
    #      'TTFT|FFTT|TTTF|FFFT|TTTF|FFFT|TFFF|FTFF|FTTT|TTTT|TFFT|FFTF|FFTF|FFFF|TFFF|TTFF', 
    #      'FFTT|TFFF|TFFF|FTTF|TFTT|FTFF|FFFT|FFTF|TFTF|TFFF|FTTF|TTFT|TFFT|FTTF|FTTT|FTTT', 
    #      'TTTT|FFTT|FFTF|TFFF|TTTF|FFFT|FFFF|TFFF|TFTF|FTFF|TFTT|FTTF|FFFT|TTFF|TTTT|TTFT', 
    #      'TTTT|TFFT|TTTF|FFFT|TFTF|FTTF|FTFT|FTFT|TTFT|FFTT|TTTF|TFFT|FFTF|FFTF|TTTF|FTTT', 
    #      'TFTT|FFTF|TFTF|FFTF|TFTF|TFTF|FFTF|FTTF|FFTT|TTTF|TFTT|FTTF|TFTT|TTTF|TFTT|TTTF'],
}
